const prompts = [
    'What is the worst advice you have given?',
    'If you saw me when I was _____________, you probably wouldn’t recognize me.',
    'If you had a name for your own memoire, what would it be called?',
    'Describe one of the worst interviews (or interview questions) that you bombed.',
    'Name one area in your life that you’ve improved on over the past year.',
    'Name one area or time in your life that you wish you could have done differently',
    'Name one area in your life that you are really proud of ',
    'Name one are in your life that, as you look back now, was pretty funny',
    'Name one are in your life that, as you look back, was EVERY bit as difficult as you thought it was.',
    'Name the weirdest relative or in-law and explain what makes them so odd.',
    'Name a weird / strange / bizarre sleeping habit about yourself?',
    'If you could pick up a hobby right now, what would it be?',
    'Name the most overrated celebrity or sports figure , in your opinion',
    'Name a “guilty pleasure” show that you’re a little embarrassed to admit you watch',
    'Name a NEW physical / health discovery or change that has taken place with you this past year.',
    'When you envision your own retirement, what do you imagine it will be like?',
    'What does REAL relaxation look like to you?',
    'Would you say you’re more of a thrill seeker or “play it safe” kind of person?',
    'Would you say you’re more of a high maintenance or low maintenance person?',
    'Would you say you’re more of an “easily bored” person or “go with the flow” person?',
    'Would you say you’re more of a people-person or introvert? Why?',
    'Would you say you spend too much time on your phone? Why / why not?',
    'When you think of a skill / ability you see in other parents, what do you admire about them?',
    'Name a trendy food or drink that drives you absolutely CRAZY!',
    'Name a genre of movies that drives you absolutely CRAZY!',
    'Name a t.v. series or show that drives you absolutely CRAZY!',
    'Name a saying / slang that drives you absolutely CRAZY!',
    'Name a habit that a relative does that drives you absolutely CRAZY!',
    'Name a habit that a coworkers does that drives you absolutely CRAZY!',
    'Name a sport that you still can’t understand WHY it’s a sport',
    'Name a weird / strange / bizarre sleeping habit about yourself',
    'Name a weird / strange / bizarre grooming habit about yourself',
    'Name a weird / strange / bizarre eating habit about yourself',
    'Name a weird / strange / bizarre morning routine habit about yourself',
    'What is the worst present you have ever received and why?',
    'What is the worst first date you have ever been on?',
    'Have you ever stalked someone on social media?',
    'What is the worst thing about selfies?',
    'What is your favorite political or celebrity scandal?',
    'If you could do anything illegal without getting caught, what would you do?',
    'What is the weirdest food (or food combination) you’ve ever tried?',
    'Did you have an imaginary friend? What was his / her name?',
    'What a reoccurring dream you’ve had for a long period of time?',
    'Who’s your favorite comedian?',
    'Have you ever been on a blind date? If so, why / why not.',
    'If someone gave you an envelope with your death date inside of it, would you open it?',
    'If you had to pick a specific time when have you been the most happy, when is that?',
    'Do you know anyone who is living their life to the fullest?',
    'What is your idea of the perfect day?',
    'When you think about the topic of the Buckeyes, in what why do you think your perspective is unique or unusual about the topic. ',
    'When you think about the topic of driving, in what why do you think your perspective is unique or unusual?',
    'When you think about the topic of retirement ,in what why do you think your perspective is unique or unusual? ',
    'When you think about the topic of personal hygiene, in what why do you think your perspective is unique or unusual? ',
    'When you think about the topic of taking cruises on cruise ships, in what why do you think your perspective is unique or unusual? ',
    'When you think about the topic of professional sports, in what why do you think your perspective is unique or unusual? ',
    'When you think about the topic of pets and animals, in what why do you think your perspective is unique or unusual? ',
    'When you think about the topic of politics, in what why do you think your perspective is unique or unusual? ',
    'When you think about the topic of health and fitness, in what why do you think your perspective is unique or unusual? ',
    'Who has been the most influential person in your life and why?',
    'What book had a big influence on you?',
    'Name one of the most ANNOYING things that drive you crazy on social media?',
    'Name something unique or unusual about your conception or your birth?',
    'If you had to pick a place to eat fast food, where are you going?',
    'If you jumped on a plane right now, where are you going?',
    'Name / describe a time you either wiped out on a bike, got stitches or hurt playing outside.',
    'Would you consider yourself superstitious? Why or why not?',
    'If you could be any kind of doctor, what kind of doctor would you like to be?',
    'If you could be any type of lawyer, what kind would you want to be and why?',
    'Who is someone that makes you laugh without trying?',
    'Name a famous person that makes you laugh the hardest.',
    'What drains your energy really fast and why do you think that is?',
    'Name one of the most shocking moments of your life.',
    'Name the most disappointing / overrated holiday you can think of?',
    'What personality trait gets you into the most trouble?',
    'Name one thing your regularly dread.',
    'How do you tend to do when under pressure? Please explain.',
    'Do you ever talk to yourself? If not, do you know someone that does?',
    'Are you a fanatic of anything? If not, name someone you know who is that’s crazy.',
    'Name a time you laughed at an inappropriate moment and what were the circumstances?',
    'Did you ever go to prom? Why / why not? Any funny memories from it?',
    'Name of the WILDEST childhood friends you’ve had. How were they crazy.',
    'Name one thing you did that your parents STILL don’t know about.',
    'Do you tend to live in the past, present or future? Explain.',
    'How tech-savvy are you? Give an example of how good / bad you are.',
    'What’s one of the most hysterical moments you’ve encountered at a wedding',
    'What’s one of the most hysterical moments you’ve encountered at family function',
    'What’s one of the most hysterical moments you’ve encountered at holiday',
    'What’s one of the most hysterical moments you’ve encountered at work',
    'What’s one of the most hysterical moments you’ve encountered at church',
    'What’s one of the most hysterical moments you’ve encountered at school',
    'Do you think your priorities have changed since you were younger?',
    'What is the most memorable lesson you learned from your parents?',
    'What does success mean to you?',
    'What is the most difficult thing you’ve ever done?',
    'What scares you most about your future?',
    'What keeps you up at night?',
    'What do I do that comforts you the most?',
    'In what ways are you most similar to me?',
    'What makes you feel discouraged?',
    'What is a significant event that has changed you?',
    'If your life was a movie, which celebrity would play you?',
    'If you won the lottery, what would be your first big splurge?',
    'What’s one movie you could watch over and over?',
    'Where’s the most exotic place you’ve ever been?',
    'If you could have picked your own name, what would it be?',
    'What is one thing you can’t live without?',
    'What is your least favorite chore?',
    'What is your earliest memory?',
    'Who are you most thankful for and why?',
    'Where do you want to go on the next family vacation?',
    'What’s the nicest thing a family member has ever done for you?',
    'What was the biggest punishment you’ve ever received?',
    'If you could describe yourself in three words, what would they be?',
    'What would be the first thing you would do if you traded places with your family member?',
    'What instrument would you like to play? Why?',
    'If you could get all your family members to donate to a charity, what would it be and why?',
    'Would you want to live on a boat, a mountain or an island?',
    'What makes you most proud?',
    'What three things are you most grateful for?',
    'Who do you count on the most for help?',
    'What would make you (if parent) most upset? A tattoo, a nose ring or a bad boyfriend / girlfriend?',
    'What would be your ideal day?',
    'What makes you the happiest?',
    'If you could spend an entire day with a family member, who would it be and why?',
    'If you could be an animal, what would it be and why?',
    'If you could be any age, what age would you choose?',
    'What’s one thing you’ve won and how did you win it?',
    'What did you think was the most challenging part of being a kid?',
    'When is the last time you laughed so hard that you cried?',
    'How long can you go without checking your phone?',
    'Have you ever really kept a New Year’s resolution?',
    'What bad habits do you wish you could stop?',
    'Do you have a morning ritual?',
    'Have you ever been stalked on social media?',
    'Can you tell when someone is lying?',
    'Are you a jealous person?',
    'If someone offered to tell you your future, would you accept it?',
    'Who’s your biggest hero?',
    'Have you ever stolen anything?',
    'If you were to remove one social media app from your phone, which would it be and why?',
    'Name something you’ve learned from a baby boomer.',
    'Name something one of your friends does that you think is incredibly sweet.',
    'Have you ever won a contest or a championship? If not, which would you want to win?',
    'Do you wished your pushed yourself harder in high school? Why / why not?',
    'Name one way you’ve tried to conquer your fears.',
    'Name something you probably take TOO seriously.',
    'Name on thing you’ve already DONE on your bucket list and 1 thing you want to do next',
    'Name a house chore you actually enjoy doing and one you HATE.',
    'If you had to have a THEMED birthday party right now, what would it be?',
    'Name a time you wished you apologized to someone but didn’t (or didn’t get a chance).',
    'Name a time you got overly emotional and you didn’t even realize that would happen.',
    'Name a favorite cousin. What makes them so special. ',
    'Name a funny saying that your parents / grandparents would use?',
    'Name a food your parents / grandparents kept around that you never understood.',
    'Name a habit your saw your parents / grandparents do that you still don’t understand.',
    'Name a petty-grudge you’ve held toward someone. What was it over?',
    'Name a time someone apologized and you still had a very hard time accepting it.',
    'What helps give you insight? Can you name a person who usually gives good advice / insight?',
    'On a scale from 1-10, how clean would you LIKE your house to be? And from 1-10, how clean is it on a day-to-day basis.',
    'Which would you rather have: a cook, housekeeper, babysitter or secretary?',
    'Name the most interesting experience you’ve ever had with the police.',
    'Name the most interesting experience you’ve had with your spouse / boyfriend / girlfriend',
    'Name the most interesting experience you’ve had at school',
    'Name the most interesting experience you’ve had in a hospital',
    'Name the most interesting experience you’ve had with a neighbor',
    'Name the most interesting experience you’ve had with your child or grandparent',
    'Name the most interesting experience you’ve had at a concert',
    'Name the most interesting experience you’ve had at a sporting event',
    'Name the most interesting experience you’ve had during a holiday',
    'Name the most interesting experience you’ve had at a party',
    'Name the most interesting experience you’ve had in middle school / high school',
    'Name the most interesting experience you’ve had at a wedding',
    'Name the most interesting experience you’ve had on a date',
    'Name the most interesting experience you’ve had at a wedding',
    'Name the most interesting experience you’ve had at a fancy place',
    'Name the most interesting experience you’ve had at work / with coworkers',
    'Name the most interesting experience you’ve had at church / bible study.',
    'Name the most interesting experience you’ve had at the ocean',
    'Name the most interesting experience you’ve had on vacation',
    'Name the most interesting experience you’ve had when at an amusement park',
    'Name the most interesting experience you’ve had during a road trip',
    'Name the most interesting experience you’ve had with a pet',
    'Name the most interesting experience you’ve had with a bike / motorcycle / moped',
    'Name the most interesting experience you’ve had on a plane or at an airport',
    'Name the most interesting experience you’ve had with you were home alone',
    'Name the most interesting experience you’ve had with a boss',
    'Name the most interesting experience you’ve had at Christmas',
    'Name the most interesting experience you’ve had when you first started driving',
    'Name the most interesting experience you’ve had when you first started your job',
    'Name the most interesting experience you’ve had with your bought your first place',
    'Name the most interesting experience you’ve had when you had a roommate(s)',
    'Name the most interesting experience you’ve had when you were ill / sick',
    'Name the most interesting experience you’ve had with a bad hair cut / hair style',
    'Name the most interesting experience you’ve had with doing something the wrong way',
    'Name the most interesting experience you’ve had with your spouse / boyfriend / girlfriend',
    'If you could name the most interesting experience you’ve had with ',
    'have tea with a fictional character, who would that be?',
    'What is your most embarrassing moment?',
    'If you were on death row, what would your last meal be?',
    'If you could sit down with your 13-year old self, what would you say?',
    'If you could only pack one thing for a trip (besides clothing) what would it be?',
    'What makes you really angry? Please be specific.',
    'What is your spirit animal? Why?',
    'What would be the title of your memoire and why?',
    'What’s your guilty pleasure?',
    'What would your theme song be if you had your own show?',
    'What bores you? Why do you think it bores you?',
    'What would you do if you were home alone and the power went out?',
    'What’s the weirdest dream you’ve ever had?',
    'If your plane was going down, who would you would call?',
    'What would your rock band / group be called?',
];
